name: Push to GHCR
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
    IMAGE_NAME: ${{ github.event.repository.name }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    strategy:
      fail-fast: false
      matrix:
        architecture: [ cpu, gpu ]
    steps:

      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest-${{ matrix.architecture }} ${{ github.sha }}-${{ matrix.architecture }}
          oci: true
          build-args: FLAVOR=${{ matrix.architecture }}
          containerfiles: |
            ./Containerfile.base
                                                                            
      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Wait  retrying
        if: steps.push.beforeoutcome == 'failure'
        run: sleep 1m

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_second_attempt
        if: steps.push.outcome == 'failure'
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
